version: '3.9'
services:
  database:
    image: postgres:16
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=myuserpassword
      - POSTGRES_DB=filmrental
    container_name: 'postgres-for-application'
    ports:
      - '5433:5432'
    volumes: 
      - rdbms_data:/var/lib/postgresql/data
    networks:
      - mynet

  test-database:
    image: postgres:16
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=myuserpassword
      - POSTGRES_DB=filmrental
    container_name: 'postgres-for-testing'
    ports:
      - '5434:5432'
    tmpfs: /var/lib/postgresql/data
    networks:
      - mynet

volumes:
  rdbms_data:
    driver: local

networks:
  mynet: